CREATE OR ALTER VIEW dbo.VW_RaceResultWithPedigree
AS
SELECT
    r.race_id,
    r.race_date       AS [日付],
    r.race_name       AS [レース名],
    r.race_class      AS [クラス],
    r.track_name      AS [場名],
    r.surface_type    AS [芝_ダート],
    r.distance_m      AS [距離],
    r.frame_no        AS [枠番],
    r.horse_no        AS [馬番],
    r.horse_name      AS [馬名],
    r.sex             AS [性],
    r.age             AS [齢],
    r.jockey_name     AS [騎手],
    r.carried_weight  AS [斤量],
    r.popularity      AS [人気],
    r.odds            AS [オッズ],
    r.finish_pos      AS [着順],
    r.finish_time     AS [走破時計],
    r.horse_weight    AS [馬体重],
    r.horse_weight_diff AS [馬体重変動],
    r.pos_corner1     AS [通過順_1角],
    r.pos_corner2     AS [通過順_2角],
    r.pos_corner3     AS [通過順_3角],
    r.pos_corner4     AS [通過順_4角],
    r.final_3f        AS [上がり],
    r.meeting         AS [開催],
    r.turn            AS [回り],
    r.going           AS [馬場],
    r.weather         AS [天気],
    r.track_id,
    r.horse_id,
    p.horse_name      AS [血統馬名],
    p.sire            AS [父],
    p.dam             AS [母],
    p.dam_sire        AS [母父],
    p.dam_dam         AS [母母],
    p.sire_sire       AS [父父],
    p.sire_dam        AS [父母]
FROM dbo.TR_RaceResult AS r
LEFT JOIN dbo.MT_HorsePedigree AS p
    ON r.horse_id = p.horse_id;
GO
