--* BackupToTempTable
DROP TABLE IF_RaceResult_CSV;

--* RestoreFromTempTable
CREATE TABLE [IF_RaceResult_CSV] (
  [race_id] NVARCHAR(12) DEFAULT NULL,
  [馬名] NVARCHAR(30) DEFAULT NULL,
  [騎手] NVARCHAR(10) DEFAULT NULL,
  [馬番] NVARCHAR(2) DEFAULT NULL,
  [走破時計] NVARCHAR(6) DEFAULT NULL,
  [オッズ] NVARCHAR(6) DEFAULT NULL,
  [通過順] NVARCHAR(12) DEFAULT NULL,
  [着順] NVARCHAR(4) DEFAULT NULL,
  [馬体重] NVARCHAR(3) DEFAULT NULL,
  [馬体重変動] NVARCHAR(4) DEFAULT NULL,
  [性] NVARCHAR(1) DEFAULT NULL,
  [齢] NVARCHAR(2) DEFAULT NULL,
  [斤量] NVARCHAR(4) DEFAULT NULL,
  [上がり] NVARCHAR(4) DEFAULT NULL,
  [人気] NVARCHAR(2) DEFAULT NULL,
  [レース名] NVARCHAR(50) DEFAULT NULL,
  [日付] NVARCHAR(12) DEFAULT NULL,
  [開催] NVARCHAR(12) DEFAULT NULL,
  [クラス] NVARCHAR(20) DEFAULT NULL,
  [芝_ダート] NVARCHAR(10) DEFAULT NULL,
  [距離] NVARCHAR(4) DEFAULT NULL,
  [回り] NVARCHAR(1) DEFAULT NULL,
  [馬場] NVARCHAR(1) DEFAULT NULL,
  [天気] NVARCHAR(1) DEFAULT NULL,
  [track_id] NVARCHAR(4) DEFAULT NULL,
  [場名] NVARCHAR(3) DEFAULT NULL
)
;

ALTER TABLE IF_RaceResult_CSV
ADD horse_id VARCHAR(20) NULL;
